[package]
name = 'CoinList'
version = '0.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = '72421d32d77f1877ded478e96f5b95914de1df91'
subdir = 'aptos-move/framework/aptos-framework'


[addresses]
coin_list = "08c805723ebc0a7fc5b7d3e7b75d567918e806b3461cb9fa21941a9edc0220bf"
